import { Event } from '../../types';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: '기존 회의',
    date: '2024-10-15',
    startTime: '09:00',
    endTime: '10:00',
    description: '기존 팀 미팅',
    location: '회의실 B',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
];

export const FILTERED_EVENTS: Event[] = [
  {
    id: '1',
    title: '이벤트 1',
    date: '2024-07-01',
    startTime: '09:00',
    endTime: '10:00',
    description: '기존 팀 미팅1',
    location: '회의실 A',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
  {
    id: '2',
    title: '이벤트 2',
    date: '2024-07-15',
    startTime: '10:00',
    endTime: '11:00',
    description: '기존 팀 미팅2',
    location: '회의실 B',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
  {
    id: '3',
    title: '이벤트 3',
    date: '2024-07-30',
    startTime: '11:00',
    endTime: '12:00',
    description: '기존 팀 미팅3',
    location: '회의실 C',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
  {
    id: '4',
    title: 'event 4',
    date: '2024-08-01',
    startTime: '11:00',
    endTime: '12:00',
    description: '기존 팀 미팅4',
    location: '회의실 D',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
];

export const SEARCH_EVENTS: Event[] = [
  {
    id: '1',
    title: '회의',
    date: '2025-02-05',
    startTime: '09:00',
    endTime: '10:00',
    description: '기존 팀 미팅1',
    location: '회의실 A',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
  {
    id: '2',
    title: '팀 회의 1',
    date: '2025-02-05',
    startTime: '10:00',
    endTime: '11:00',
    description: '기존 팀 미팅2',
    location: '회의실 B',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
  {
    id: '3',
    title: '팀 회의 2',
    date: '2025-02-05',
    startTime: '11:00',
    endTime: '12:00',
    description: '기존 팀 미팅3',
    location: '회의실 C',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
];
